### ISSUE TITLE
请问freqitem和hashtree并没有使用是吗？

### ISSUE THREAD

**Issue by Liane-Wang** [Moonshile/ChineseWordSegmentation#10]

**Comment by Moonshile** [comment]
在分词中没有使用。

**Comment by Liane-Wang** [comment]
那请问这两个模块是用作什么的呢？谢谢！

**Comment by Liane-Wang** [comment]
分词之后统计词频的吗？

**Comment by Liane-Wang** [comment]
感谢解惑。代码写得十分完美。

**Comment by Moonshile** [comment]
> 那请问这两个模块是用作什么的呢？谢谢！

顾名思义，频繁项集分析，算是在分词之后对文本内容进行分析的一个使用案例。

**Comment by Liane-Wang** [comment]
> > 那请问这两个模块是用作什么的呢？谢谢！
> 
> 顾名思义，频繁项集分析，算是在分词之后对文本内容进行分析的一个使用案例。

谢谢。
