### ISSUE TITLE
 return sorted(indexes,key=lambda m,n:doc[m:n])报错

### ISSUE THREAD

**Issue by chenzk1993** [Moonshile/ChineseWordSegmentation#2]
return sorted(indexes,key=lambda m,n:doc[m:n])报 TypeError: <lambda>() missing 1 required positional argument: 'n'错误，我用的是python3.6. 希望得到你的帮助。谢谢！

**Comment by mumutu66** [comment]
@ZhikuoChen  it seems above 3.x lambda only accpet one argument  change it to  lambda x : doc[x[0], x[1]]

**Comment by Moonshile** [comment]
@mumutu66 correct.

**Comment by Moonshile** [comment]
Already upgrade to python 3. Thanks PR of @bung87!
