### ISSUE TITLE
怎么用 没看懂

### ISSUE THREAD

**Issue by zhfff4869** [Moonshile/ChineseWordSegmentation#6]
怎么用啊 一点都不会

**Comment by Moonshile** [comment]
参考README

**Comment by zhfff4869** [comment]
懂了，但是效果似乎不好啊。好多词都检测不出来，都分成一个字一个字的了

**Comment by Moonshile** [comment]
可以调一调参数，比如`min_aggregation`和`min_entropy`，或者增大文本。毕竟这种方法比较简单粗暴，确实有时候效果不太好。

**Comment by liane886** [comment]
不是用readme里的segSentence function， 而是words

**Comment by liane886** [comment]
先把代码看看再来问人。。。

**Comment by liane886** [comment]
应该不是用readme里的segSentence function吧。要得出分词的话得用words

**Comment by Liane-Wang** [comment]
应该不是用readme里的seg'Sentence函数吧 是不是得用words

**Comment by Moonshile** [comment]
> 应该不是用readme里的seg'Sentence函数吧 是不是得用words

genWords 是获得词表

**Comment by Liane-Wang** [comment]
不是genWords。是这个：
https://github.com/Moonshile/ChineseWordSegmentation/blob/9203eb1f572f2999221da1d98677ea20475502e6/wordseg/wordseg.py#L164
